### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by TomasVotruba** [Arachne/Doctrine#1]
Do you plan to add readme? I'd like to know features at this package, since it looks interesting at first sight.

**Comment by enumag** [comment]
The only useful thing it has right now is this [listener](https://github.com/arachne/Doctrine/blob/master/src/Validator/ValidatorListener.php) from Majkl578.

The other classes are for usage with my own private packages so I was actually thinking about removing this package from github entirely.

**Comment by enumag** [comment]
@TomasVotruba Documentation finally added! Any feedback is welcomed. ;-)
